import type { Metadata } from "next";

import "../globals.css";

import { Footer } from "../../components/client/layouts/Footer";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "@/src/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
   const { locale } = await params;
 const messages = await getMessages({ locale }); 

 if(!hasLocale(routing.locales,locale)){
  notFound()
 }
  return (

    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages} >
        <main>{children}</main>
        <Footer />
        </NextIntlClientProvider>
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 3000,
          }}
        />
      </body>
    </html>
    
  );
}
