name: Build & Push Images to ACR

on:
  push:
    branches: [ "main", "dev" ]
  workflow_call:        
    inputs:
      branch:
        required: true
        type: string
      run_number:
        required: true
        type: string
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Thêm Buildx để dùng được cache
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: hotelmanagementregistry123.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Set ENV TAG
      run: |
        BRANCH="${{ inputs.branch || github.ref_name }}"
        if [[ "$BRANCH" == "main" ]]; then
          echo "ENV_TAG=prod" >> $GITHUB_ENV
        else
          echo "ENV_TAG=dev" >> $GITHUB_ENV
        fi

    - name: Build & Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./hotel-management-be
        file: ./hotel-management-be/Dockerfile
        push: true
        tags: |
          hotelmanagementregistry123.azurecr.io/hotelmanagementbe:${{ env.ENV_TAG }}-${{ inputs.run_number || github.run_number }}
          hotelmanagementregistry123.azurecr.io/hotelmanagementbe:${{ env.ENV_TAG }}
        cache-from: type=registry,ref=hotelmanagementregistry123.azurecr.io/hotelmanagementbe:cache-${{ env.ENV_TAG }}
        cache-to: type=registry,ref=hotelmanagementregistry123.azurecr.io/hotelmanagementbe:cache-${{ env.ENV_TAG }},mode=max

    - name: Build & Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./hotel-management
        file: ./hotel-management/Dockerfile
        push: true
        build-args: ENV_FILE=.env.${{ env.ENV_TAG }}
        tags: |
          hotelmanagementregistry123.azurecr.io/hotelmanagementfe:${{ env.ENV_TAG }}-${{ inputs.run_number || github.run_number }}
          hotelmanagementregistry123.azurecr.io/hotelmanagementfe:${{ env.ENV_TAG }}
        cache-from: type=registry,ref=hotelmanagementregistry123.azurecr.io/hotelmanagementfe:cache-${{ env.ENV_TAG }}
        cache-to: type=registry,ref=hotelmanagementregistry123.azurecr.io/hotelmanagementfe:cache-${{ env.ENV_TAG }},mode=max