name: Deploy to Azure Container Apps

on:
  workflow_run:
    workflows: ["Build & Push Images to ACR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    #  Login Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    #  Xác định môi trường
    - name: Set ENV TAG
      run: |
        if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
          echo "ENV_TAG=prod" >> $GITHUB_ENV
        else
          echo "ENV_TAG=dev" >> $GITHUB_ENV
        fi

    #  Deploy Backend
    - name: Deploy Backend
      run: |
        az containerapp update \
          --name hotelmanagement-be \
          --resource-group hotel-management-rg \
          --image hotelmanagementregistry123.azurecr.io/hotelmanagementbe:$ENV_TAG

    #  Deploy Frontend
    - name: Deploy Frontend
      run: |
        az containerapp update \
          --name hotelmanagement-fe \
          --resource-group hotel-management-rg \
          --image hotelmanagementregistry123.azurecr.io/hotelmanagementfe:$ENV_TAG